SELECT SUM(TotalCount) AS "Total Tuples"
FROM (
    SELECT COUNT(*) AS TotalCount FROM ESTELLEDENIS.ANNUALSURFACETEMPCHANGE
    UNION ALL
    SELECT COUNT(*) FROM ESTELLEDENIS.ANNUALSURFACETEMPCHANGENORMALIZED
    UNION ALL
    SELECT COUNT(*) FROM ESTELLEDENIS.CHANGEINMEANSEALEVELS
    UNION ALL
    SELECT COUNT(*) FROM ESTELLEDENIS.CITIES
    UNION ALL
    SELECT COUNT(*) FROM ESTELLEDENIS.CITIESOFTHEWORLD
    UNION ALL
    SELECT COUNT(*) FROM ESTELLEDENIS.CO2EMISSIONS
    UNION ALL
    SELECT COUNT(*) FROM ESTELLEDENIS.CO2INDUSTRIES
    UNION ALL
    SELECT COUNT(*) FROM ESTELLEDENIS.CO2INDUSTRIESNORMALIZED
    UNION ALL
    SELECT COUNT(*) FROM ESTELLEDENIS.COUNTRIES
    UNION ALL
    SELECT COUNT(*) FROM ESTELLEDENIS.COUNTRYGDP
    UNION ALL
    SELECT COUNT(*) FROM ESTELLEDENIS.FLIGHTDELAYS
    UNION ALL
    SELECT COUNT(*) FROM ESTELLEDENIS.GLOBALCO2
    UNION ALL
    SELECT COUNT(*) FROM ESTELLEDENIS.GLOBALLANDTEMPERATURESBYCOUNTRY
    UNION ALL
    SELECT COUNT(*) FROM ESTELLEDENIS.USWEATHEREVENTS
    UNION ALL
    SELECT COUNT(*) FROM ESTELLEDENIS.USWEATHEREVENTSSCALE
    UNION ALL
    SELECT COUNT(*) FROM ESTELLEDENIS.WORLDPOPULATION
    UNION ALL
    SELECT COUNT(*) FROM ESTELLEDENIS.ZIPCODEINDEX
) TotalTableCount;

SELECT SUM(TotalCount) AS "Total Tuples"
FROM (
    SELECT COUNT(*) AS TotalCount FROM ANNUALSURFACETEMPCHANGE
    UNION ALL
    SELECT COUNT(*) FROM ANNUALSURFACETEMPCHANGENORMALIZED
    UNION ALL
    SELECT COUNT(*) FROM CHANGEINMEANSEALEVELS
    UNION ALL
    SELECT COUNT(*) FROM CITIES
    UNION ALL
    SELECT COUNT(*) FROM CITIESOFTHEWORLD
    UNION ALL
    SELECT COUNT(*) FROM CO2EMISSIONS
    UNION ALL
    SELECT COUNT(*) FROM CO2INDUSTRIES
    UNION ALL
    SELECT COUNT(*) FROM CO2INDUSTRIESNORMALIZED
    UNION ALL
    SELECT COUNT(*) FROM COUNTRIES
    UNION ALL
    SELECT COUNT(*) FROM COUNTRYGDP
    UNION ALL
    SELECT COUNT(*) FROM FLIGHTDELAYS
    UNION ALL
    SELECT COUNT(*) FROM GLOBALCO2
    UNION ALL
    SELECT COUNT(*) FROM GLOBALLANDTEMPERATURESBYCOUNTRY
    UNION ALL
    SELECT COUNT(*) FROM USWEATHEREVENTS
    UNION ALL
    SELECT COUNT(*) FROM USWEATHEREVENTSSCALE
    UNION ALL
    SELECT COUNT(*) FROM WORLDPOPULATION
    UNION ALL
    SELECT COUNT(*) FROM ZIPCODEINDEX
) TotalTableCount;

SELECT
  'ANNUALSURFACETEMPCHANGE' AS "TABLES",
  COUNT(*) AS row_count
FROM
  ANNUALSURFACETEMPCHANGE
UNION ALL
SELECT
  'ANNUALSURFACETEMPCHANGENORMALIZED' AS ANNUALSURFACETEMPCHANGENORMALIZED,
  COUNT(*) AS row_count
FROM
  ANNUALSURFACETEMPCHANGENORMALIZED
UNION ALL
SELECT
  'CHANGEINMEANSEALEVELS' AS CHANGEINMEANSEALEVELS,
  COUNT(*) AS row_count
FROM
  CHANGEINMEANSEALEVELS
UNION ALL
SELECT
  'CITIES' AS CITIES,
  COUNT(*) AS row_count
FROM
  CITIES
  UNION ALL
SELECT
  'CITIESOFTHEWORLD' AS CITIESOFTHEWORLD,
  COUNT(*) AS row_count
FROM
  CITIESOFTHEWORLD
  UNION ALL
SELECT
  'CO2EMISSIONS' AS CO2EMISSIONS,
  COUNT(*) AS row_count
FROM
  CO2EMISSIONS
  UNION ALL
SELECT
  'CO2INDUSTRIES' AS CO2INDUSTRIES,
  COUNT(*) AS row_count
FROM
  CO2INDUSTRIES
  UNION ALL
SELECT
  'CO2INDUSTRIESNORMALIZED' AS CO2INDUSTRIESNORMALIZED,
  COUNT(*) AS row_count
FROM
  CO2INDUSTRIESNORMALIZED
  UNION ALL
SELECT
  'COUNTRIES' AS COUNTRIES,
  COUNT(*) AS row_count
FROM
  COUNTRIES
  UNION ALL
SELECT
  'COUNTRYGDP' AS COUNTRYGDP,
  COUNT(*) AS row_count
FROM
  COUNTRYGDP
  UNION ALL
SELECT
  'FLIGHTDELAYS' AS FLIGHTDELAYS,
  COUNT(*) AS row_count
FROM
  FLIGHTDELAYS
  UNION ALL
SELECT
  'GLOBALCO2' AS GLOBALCO2,
  COUNT(*) AS row_count
FROM
  GLOBALCO2
  UNION ALL
SELECT
  'GLOBALLANDTEMPERATURESBYCOUNTRY' AS GLOBALLANDTEMPERATURESBYCOUNTRY,
  COUNT(*) AS row_count
FROM
  GLOBALLANDTEMPERATURESBYCOUNTRY
  UNION ALL
SELECT
  'USWEATHEREVENTS' AS USWEATHEREVENTS,
  COUNT(*) AS row_count
FROM
  USWEATHEREVENTS
  UNION ALL
SELECT
  'USWEATHEREVENTSSCALE' AS USWEATHEREVENTSSCALE,
  COUNT(*) AS row_count
FROM
  USWEATHEREVENTSSCALE
  UNION ALL
SELECT
  'WORLDPOPULATION' AS WORLDPOPULATION,
  COUNT(*) AS row_count
FROM
  WORLDPOPULATION
  UNION ALL
SELECT
  'ZIPCODEINDEX' AS ZIPCODEINDEX,
  COUNT(*) AS row_count
FROM
  ZIPCODEINDEX
  UNION ALL
SELECT
  'Total' AS table_name,
  SUM(row_count) AS row_count
FROM (
SELECT COUNT(*) AS row_count FROM ANNUALSURFACETEMPCHANGE
UNION ALL
SELECT COUNT(*) AS row_count FROM ANNUALSURFACETEMPCHANGENORMALIZED
UNION ALL
SELECT COUNT(*) AS row_count FROM CHANGEINMEANSEALEVELS
UNION ALL
SELECT COUNT(*) AS row_count FROM CITIES
UNION ALL
SELECT COUNT(*) AS row_count FROM CITIESOFTHEWORLD
UNION ALL
SELECT COUNT(*) AS row_count FROM CO2EMISSIONS
UNION ALL
SELECT COUNT(*) AS row_count FROM CO2INDUSTRIES
UNION ALL
SELECT COUNT(*) AS row_count FROM CO2INDUSTRIESNORMALIZED
UNION ALL
SELECT COUNT(*) AS row_count FROM COUNTRIES
UNION ALL
SELECT COUNT(*) AS row_count FROM COUNTRYGDP
UNION ALL
SELECT COUNT(*) AS row_count FROM FLIGHTDELAYS
UNION ALL
SELECT COUNT(*) AS row_count FROM GLOBALCO2
UNION ALL
SELECT COUNT(*) AS row_count FROM GLOBALLANDTEMPERATURESBYCOUNTRY
UNION ALL
SELECT COUNT(*) AS row_count FROM USWEATHEREVENTS
UNION ALL
SELECT COUNT(*) AS row_count FROM USWEATHEREVENTSSCALE
UNION ALL
SELECT COUNT(*) AS row_count FROM WORLDPOPULATION
UNION ALL
SELECT COUNT(*) AS row_count FROM ZIPCODEINDEX
);